[package]
name = "pixels-graphics-lib"
version = "0.9.2"
edition = "2021"
authors = ["Emma Britton <emmabritton@pm.me>"]
description = "Simple wrapper library around Pixels/Buffer Graphics"
license-file = "LICENSE"
repository = "https://github.com/emmabritton/pixel-graphics-lib"
readme = "README.md"
keywords = ["graphics", "gamedev", "pixels", "simple"]
categories = ["graphics", "game-development"]

[features]
default = ["window_prefs"]
window_prefs = ["directories", "serde_json", "serde"]

[dependencies]
pixels = "0.12.1"
winit = "0.28.2"
winit_input_helper = "0.14.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"], optional = true }
directories = { version = "5.0.0", optional = true }
serde_json = { version = "1.0", optional = true }
graphics-shapes = "0.1.11"
buffer-graphics-lib = { version = "0.10.3", features = ["image_loading", "ici", "serde_derive"] }
rustc-hash = "1.1.0"

[dev-dependencies]
fastrand = "1.6"
anyhow = "1.0"
