[package]
name = "pixels-graphics-lib"
version = "0.6.0"
edition = "2021"
authors = ["Ray Britton <raybritton@pm.me>"]
description = "Simple wrapper library around Pixels/Buffer Graphics"
license-file = "LICENSE"
repository = "https://github.com/raybritton/rust-graphics-lib"
readme = "README.md"
homepage = "https://github.com/raybritton/rust-graphics-lib"
keywords = ["graphics", "gamedev", "pixels", "simple"]
categories = ["graphics", "game-development"]

[features]
default = ["window_prefs"]
window_prefs = ["directories", "serde_json", "serde"]

[dependencies]
pixels = "0.8.0"
winit = "0.27.2"
winit_input_helper = "0.13.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"], optional = true }
directories = {version = "4.0", optional = true }
serde_json = {version = "1.0", optional = true }
buffer-graphics-lib = "0.6.0"

[dev-dependencies]
fastrand = "1.6"
anyhow = "1.0"
graphics-shapes = "0.1.2"
