[package]
name = "pixels-graphics-lib"
version = "0.13.10"
edition = "2021"
authors = ["Emma Britton <emmabritton@pm.me>"]
description = "Simple wrapper library around Pixels/Buffer Graphics"
license-file = "LICENSE"
repository = "https://github.com/emmabritton/pixel-graphics-lib"
readme = "README.md"
keywords = ["graphics", "gamedev", "pixels", "simple"]
categories = ["graphics", "game-development"]

[features]
default = ["window_prefs", "sound", "controller"]
window_prefs = ["simple-game-utils/prefs"]
controller = ["serde", "simple-game-utils/controller"]
sound = ["simple-game-utils/sound"]
file_dialogs = ["directories"]

[dependencies]
pixels = "0.13.0"
winit = { version = "0.29.4", features = ["rwh_05"] }
winit_input_helper = "0.15.1"
thiserror = "1.0.51"
serde = { version = "1.0.193", features = ["derive"], optional = true }
directories = { version = "5.0.1", optional = true }
graphics-shapes = "0.2.4"
buffer-graphics-lib = { version = "0.12.4", features = ["image_loading", "ici", "serde_derive"] }
rustc-hash = "1.1.0"
simple-game-utils = { version = "0.3.4", features= [] }
fnv = "1.0.7"

[dev-dependencies]
fastrand = "2.0.0"
anyhow = "1.0"
