on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install linux libs
        run: sudo apt-get update; sudo apt-get install --no-install-recommends pkg-config build-essential gcc-multilib libudev-dev libjack-jackd2-dev libjack-jackd2-0 libasound2-dev alsa
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: cargo fmt --all -- --check
      - run: cargo clippy --features "pixels" --all-targets -- -D clippy::all
      - run: cargo clippy --features "softbuffer" --all-targets -- -D clippy::all
      - run: cargo publish --token ${CRATES_TOKEN} --features "pixels"
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}